server.port: 8100

spring.application.name: demo
spring.jackson.time-zone: GMT+8

spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB

## Redis的默认配置
spring.redis.port: 6379
spring.redis.database: 6
spring.redis.timeout: 60000
spring.redis.jedis.pool.max-active: -1
spring.redis.jedis.pool.max-wait: -1
spring.redis.jedis.pool.max-idle: 20
spring.redis.jedis.pool.min-idle: 10

mybatis.mapper-locations: classpath:*.xml

server.compression.enabled: true
server.compression.mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain